{
 "title": "Traffic",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Application", "label": "Application", "query": "%" },
   { "name": "IP", "label": "IP", "query": "%" },
   { "name": "Network", "label": "Network", "query": "Global,Internet,Internal" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Country",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    if(country = '', 'Unknown', toString(country)) AS country_code,\n    uniqExact(remote_ip)                           AS unique_ip_count\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host       LIKE '%${Application}%'\n  -- 暂时注释掉 IP 过滤，先看全局分布\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY country_code\nORDER BY unique_ip_count DESC"
    }
   ]
  },
  {
   "title": "Accumulative Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH first_seen AS (\n  SELECT\n    remote_ip,\n    min(ts) AS first_seen\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host       LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n  GROUP BY remote_ip\n),\nnew_ips_per_bucket AS (\n  SELECT\n    toStartOfMinute(first_seen) AS bucket,   -- 这一行可以改成你想要的时间粒度\n    count() AS new_ips\n  FROM first_seen\n  GROUP BY bucket\n)\nSELECT\n  bucket AS time,\n  sum(new_ips) OVER (ORDER BY bucket ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_unique_ips\nFROM new_ips_per_bucket\nORDER BY bucket;\n"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(ts) as \"time\", count(ts) FROM \"logs\".\"caddy_requests\"\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n  GROUP BY time"
    }
   ]
  },
  {
   "title": "Method Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  method                        AS method,\n  count()                       AS request_count\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host       LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY method\nORDER BY request_count DESC\n"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  quantile(0.95)(duration_ms) AS current_p95_response_time_ms\nFROM logs.caddy_requests\nWHERE ts BETWEEN $__fromTime AND $__toTime\n  AND status   != '101'\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n"
    }
   ]
  },
  {
   "title": "Requests Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(ts)                          AS \"time\",\n  quantile(0.95)(duration_ms)                  AS p95_response_time_ms\nFROM \"logs\".\"caddy_requests\"\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND status   != '101'\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "P80 Latency",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  quantile(0.80)(duration_ms) AS current_p95_response_time_ms\nFROM logs.caddy_requests\nWHERE ts BETWEEN $__fromTime AND $__toTime\n  AND status   != '101'\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n"
    }
   ]
  },
  {
   "title": "Middle Latency",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  quantile(0.5)(duration_ms) AS current_median_response_time_ms\nFROM logs.caddy_requests\nWHERE ts BETWEEN $__fromTime AND $__toTime\n  AND status   != '101'\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n"
    }
   ]
  },
  {
   "title": "Requests By Unique IP Count (IPs)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    host                            AS Application,\n    uniqExact(remote_ip)            AS unique_ip_count\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY Application\nORDER BY unique_ip_count DESC\n\n"
    }
   ]
  },
  {
   "title": "Total Time costs (Seconds)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n    host                            AS Application,\n    sum(duration_ms)/1000                AS total_duration_seconds\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND status != '101'\n  AND host LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY Application\nORDER BY total_duration_seconds DESC"
    }
   ]
  },
  {
   "title": "Total Bytes Sent (MB)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    host                            AS Application,\n    sum(bytes_sent)                AS total_duration_seconds\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND status != '101'\n  AND host LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY Application\nORDER BY total_duration_seconds DESC"
    }
   ]
  },
  {
   "title": "500 Failure Rate%",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    host                                       AS Application,\n    round(countIf(status >= 500) / count() * 100, 2) AS failure_rate_percent\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY Application\nORDER BY failure_rate_percent DESC\n"
    }
   ]
  },
  {
   "title": "Average Throughput",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(bytes_sent) / (($__toTime) - ($__fromTime)) AS bytes_per_second\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host      LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n"
    }
   ]
  },
  {
   "title": "Average Rps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count() / dateDiff('second', $__fromTime, $__toTime) AS avg_requests_per_second\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host      LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n"
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   toString(status) AS status,\n  count()                       AS request_count\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host       LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY status\nORDER BY request_count DESC\n"
    }
   ]
  },
  {
   "title": "Total Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(bytes_sent)\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nLIMIT 200"
    }
   ]
  },
  {
   "title": "Incoming Unique IPs Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(ts)             AS \"time\",\n  uniqExact(remote_ip)            AS unique_ip_count\nFROM \"logs\".\"caddy_requests\"\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Processing Requests Total Time Costs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(ts)             AS \"time\",\n  sum(duration_ms)           AS total_duration_ms\nFROM \"logs\".\"caddy_requests\"\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Upload Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeInterval(ts) AS time,\n    sum(bytes_sent) / $__interval_s AS bytes_per_second\nFROM logs.caddy_requests\nWHERE\n    $__timeFilter(ts)\n    AND host LIKE '%${Application}%'\n    AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY\n    time\nORDER BY\n    time ASC"
    }
   ]
  },
  {
   "title": "Requests 500 Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(ts)             AS \"time\",\n  countIf(status >= 500)          AS failure_count\nFROM \"logs\".\"caddy_requests\"\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Requests By Count",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    host as Application,\n    count()                AS requests\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY Application\nORDER BY requests DESC\n\n"
    }
   ]
  },
  {
   "title": "Hot Interfaces",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    concat(host, splitByChar('?', uri)[1])   AS Path,\n    count()                                       AS requests\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY Path\nORDER BY requests DESC\n"
    }
   ]
  },
  {
   "title": "Slow Interface",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    concat(host, splitByChar('?', uri)[1])   AS Path,\n    avg(duration_ms)                               AS avg_response_time_ms\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n  AND status != '101'\nGROUP BY Path\nORDER BY avg_response_time_ms DESC\n"
    }
   ]
  },
  {
   "title": "Sent data to IPs",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 4, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  remote_ip,\n  sum(bytes_sent) AS total_bytes_sent\nFROM \"logs\".\"caddy_requests\"\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host      LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY remote_ip\nORDER BY total_bytes_sent DESC;\n"
    }
   ]
  },
  {
   "title": "Incoming IPs",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT remote_ip, COUNT(*) AS count\nFROM \"logs\".\"caddy_requests\"\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY remote_ip\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Error Rate Interface",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    concat(host, splitByChar('?', uri)[1])   AS Path,\n    round(countIf(status >= 500) / count() * 100, 2) AS failure_rate_percent\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY Path\nORDER BY failure_rate_percent DESC\n"
    }
   ]
  },
  {
   "title": "RAW",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n    ts, remote_ip, method, host, uri, status, bytes_sent, duration_ms, country\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nORDER BY ts DESC\nLIMIT 200"
    }
   ]
  },
  {
   "title": "Upgrade Unique IPs Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(ts)             AS \"time\",\n  uniqExact(remote_ip)            AS unique_ip_count\nFROM \"logs\".\"caddy_requests\"\nWHERE uri like '/upgrade%'\n  AND ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Error Interface",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    concat(host, splitByChar('?', uri)[1])   AS Path,\n    count()                                       AS requests\nFROM logs.caddy_requests\nWHERE ( ts >= $__fromTime AND ts <= $__toTime )\n  AND host     LIKE '%${Application}%'\n  AND remote_ip LIKE '%${IP}%'\n  AND (\n    ('${Network}' = 'Global') OR\n    ('${Network}' = 'Internal' AND (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    )) OR\n    ('${Network}' = 'Internet' AND NOT (\n        remote_ip LIKE '10.%' OR \n        remote_ip LIKE '172.16.%' OR remote_ip LIKE '172.17.%' OR remote_ip LIKE '172.18.%' OR remote_ip LIKE '172.19.%' OR\n        remote_ip LIKE '172.20.%' OR remote_ip LIKE '172.21.%' OR remote_ip LIKE '172.22.%' OR remote_ip LIKE '172.23.%' OR\n        remote_ip LIKE '172.24.%' OR remote_ip LIKE '172.25.%' OR remote_ip LIKE '172.26.%' OR remote_ip LIKE '172.27.%' OR\n        remote_ip LIKE '172.28.%' OR remote_ip LIKE '172.29.%' OR remote_ip LIKE '172.30.%' OR remote_ip LIKE '172.31.%' OR\n        remote_ip LIKE '192.168.%'\n    ))\n  )\n  AND status >= 500\nGROUP BY Path\nORDER BY requests DESC\n"
    }
   ]
  }
 ]
}